// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  event1: require('../Images/event1.png'),
  event2: require('../Images/event2.png'),
  event3: require('../Images/event3.png'),
  event4: require('../Images/event4.png'),
  event5: require('../Images/event5.png'),
  event6: require('../Images/event6.png'),
  team1: require('../Images/team1.png'),
  team2: require('../Images/team2.png'),
  team3: require('../Images/team3.png'),
  team4: require('../Images/team4.png'),
  team5: require('../Images/team5.png'),
  quiz1: require('../Images/quiz1.png'),
  quiz2: require('../Images/quiz2.png'),
  partner1: require('../Images/gdg.png'),
  partner2: require('../Images/rebo.png'),
  map: require('../Images/map.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  computercell: require('../Images/computercell.png')
}

export default images
