# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ComputerCell' do
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.13.0'
  pod 'Firebase/Auth', '~> 6.13.0'
  pod 'Firebase/Database', '~> 6.13.0'
  pod 'Firebase/DynamicLinks', '~> 6.13.0'
  # Comment the next line if you don't want to use dynamic frameworks


  # Pods for ComputerCell

  target 'ComputerCell-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ComputerCellTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ComputerCell-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks


  # # Pods for ComputerCell-tvOS

  # target 'ComputerCell-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
